### ISSUE TITLE
exported pdf not opened by preview.app

### ISSUE THREAD

**Issue by tbates** [jeroen/rsvg#22]
```R
tmp = DiagrammeR::grViz('digraph{a->b; c->a; c->b; c->d;}') # make a graph
tmp = DiagrammeRsvg::export_svg(tmp) #export as SVG
tmp = charToRaw(tmp) # flatten
rsvg::rsvg_png(tmp, "g.png") # save as png in current working directory
rsvg::rsvg_pdf(tmp, "g.pdf") # save as pdf
```

preview.app  says the pdf is damaged or in an unrecognised format

If you open the png, all is fine. And the pdf file shows a valid preview-image if you do quick-view in the Finder (on MacOS 11.2).

Not sure if this is an Apple Preview.app bug, or an rsvg pdf export problem, or something else.

Here's the miscreant file

[g.pdf](https://github.com/jeroen/rsvg/files/5860393/g.pdf)

**Comment by jeroen** [comment]
The code you give above seems to work on my mac. Are you using the latest version of rsvg?

**Comment by tbates** [comment]
Thanks for looking!

I'm on CRAN `packageVersion("rsvg")` [1] ‘2.1’

But the example pdf opens for you in preview.app, it may be a bug in preview Version 11.0 (1018.2)

Will pass on to Apple feedback.
