### ISSUE TITLE
package ‘rsvg’ is not available for this version of R

### ISSUE THREAD

**Issue by junmeiW** [jeroen/rsvg#25]
Hi, 
I have installed the librsvg2-dev in my linux, when i install the rsvg package( my R 4.0.3 (2020-10-10)), it always reports: package ‘rsvg’ is not available for this version of R

how to fix this?

**Comment by jeroen** [comment]
You probably have some connection error. Can you please show the full output?

```r
install.packages('rsvg', repos = 'https://cran.r-project.org')
```

**Comment by junmeiW** [comment]
Thanks, I've installed this package successfully!
Previously, I used the code `install.packages("rsvg", repos = "http://vnijs.github.io/radiant_miniCRAN/")` referred from others and got that error .
