### ISSUE TITLE
install the rsvg trigger error

### ISSUE THREAD

**Issue by honghh2018** [jeroen/rsvg#26]
Hi @jeroen ,
    I am very confused that the rsvg R package occurred below error:
![image](https://user-images.githubusercontent.com/41668708/115110073-0874dd80-9fac-11eb-9251-86f4e92791f2.png)
    I already install the librsvg2-devel using yum install command and i can locate the librsvg directory, but it still complaint the
 the error like above i post.
     So how could i fix this issue?
    any advice would be appreciated.
     hanhuihong
The librsvg locate:
 
![image](https://user-images.githubusercontent.com/41668708/115110146-7f11db00-9fac-11eb-8986-002011c0b03c.png)

**Comment by jeroen** [comment]
If you're using anaconda, it's better to install the package via https://anaconda.org/conda-forge/r-rsvg

**Comment by honghh2018** [comment]
It work, Thank you very much!
