### ISSUE TITLE
CRAN build failing for OS X

### ISSUE THREAD

**Issue by khoran** [jeroen/rsvg#7]
It seems like the build for rsvg on OS X is failing on CRAN: https://cran.r-project.org/web/checks/check_results_rsvg.html

I'd really like to be able to use this package as a dependency for a bioconductor (bioconductor.org) package, but they require that packages be available on CRAN and available for Linux, Windows, and Mac. 

Thanks.

**Comment by jeroen** [comment]
I submitted a new version to CRAN, fingers crossed. Hopefully be there in 24 hours or so.

**Comment by jeroen** [comment]
The binaries are on CRAN now.

**Comment by khoran** [comment]
That's great, thanks.
